-- TURNO PROGRAMMATO
CREATE TABLE TURNO_PROGRAMMATO(
data_oraIngresso DATE,
data_oraUscita DATE,
data_oraIngressoeff DATE,
CONSTRAINT PK_TURNO_PRO PRIMARY KEY (data_oraIngresso),
CONSTRAINT FK_TURNO_EFF FOREIGN KEY (data_oraIngressoeff) REFERENCES TURNO_EFFETTUATO (data_oraIngressoeff)
);

-- TURNO EFFETTUATO
CREATE TABLE TURNO_EFFETTUATO(
data_oraIngressoeff DATE,
data_oraUscita_eff DATE,
numTesserino NUMBER(11),
CONSTRAINT PK_TURNO_PROG PRIMARY KEY (data_oraIngressoeff),
CONSTRAINT FK_PERSON FOREIGN KEY (numTesserino) REFERENCES PERSONALE (numTesserino)
);

-- PERSONALE
CREATE TABLE PERSONALE(
numTesserino NUMBER(11),
Nome VARCHAR(10),
Cognome VARCHAR(20),
Mansione VARCHAR(15),
CONSTRAINT PK_PERSONALE PRIMARY KEY (numTesserino)
);

--STIPENDIO
CREATE TABLE STIPENDIO(
cod_bustapaga NUMBER(5),
Data_accredito DATE,
importo	NUMBER(6),
numTesserino NUMBER(11),
CONSTRAINT PK_STIPENDIO PRIMARY KEY (cod_bustapaga),
CONSTRAINT FK_PERSONAL FOREIGN KEY (numTesserino) REFERENCES PERSONALE (numTesserino)
);

--EVENTO 
CREATE TABLE EVENTO(
numEvento NUMBER(5),
Data_evento DATE,
Durata VARCHAR(10),
Tipo VARCHAR(15),
Capienza NUMBER(3),
numTesserino NUMBER(11),
CONSTRAINT PK_EVENT PRIMARY KEY (numEvento),
CONSTRAINT FK_PERS FOREIGN KEY (numTesserino) REFERENCES PERSONALE (numTesserino)
);

--CLIENTE
CREATE TABLE CLIENTE
(
	CF VARCHAR(16),
	Nome VARCHAR(10),
	Cognome VARCHAR(20),
	DN DATE,
	Telefono NUMBER(15),
	Via VARCHAR(20),
	Città VARCHAR(10),
	CAP NUMBER(10),
	codCarta NUMBER(5) NOT NULL,
	CONSTRAINT PK_CLIENT PRIMARY KEY (CF),
	CONSTRAINT FK_ABBONAMENT FOREIGN KEY (codCarta) REFERENCES ABBONAMENTO (codCarta)
);

--ABBONAMENTO
CREATE TABLE ABBONAMENTO (
codCarta NUMBER(5),
Prezzo NUMBER(5),
Durata VARCHAR(12),
Sconto NUMBER(5),
data_scadenza DATE NULL,
CONSTRAINT PK_ABBONAMENTO PRIMARY KEY (codCarta)
);

--FUMETTO
CREATE TABLE FUMETTO
(
	ISBN VARCHAR(20),
	Nome VARCHAR(20),
	Genere VARCHAR(10),
	Prezzo NUMBER(3,2),
	Num_scaffale NUMBER(2),
	codCasaEdi NUMBER(10),
	CONSTRAINT PK_FUMETTO PRIMARY KEY (ISBN),
	CONSTRAINT FK_MAGAZZIN FOREIGN KEY (Num_scaffale) REFERENCES MAGAZZINO (Num_scaffale),
	CONSTRAINT FK_CASAEDI FOREIGN KEY (codCasaEdi) REFERENCES CASA_EDITRICE	(codCasaEdi)
);

--MAGAZZINO
CREATE TABLE MAGAZZINO
(
	Num_scaffale NUMBER(2),
	Reparto VARCHAR(10),
	Num_piano NUMBER(2),
	CONSTRAINT PK_MAGAZZ PRIMARY KEY (Num_scaffale)
);

--CASA EDITRICE
CREATE TABLE CASA_EDITRICE (
	codCasaEdi NUMBER(10),
    Nome VARCHAR (15),
    Città VARCHAR (10),
    CONSTRAINT PK_CASA_EDITRICE PRIMARY KEY (codCasaEdi)
	);
	
--FORNITORE
CREATE TABLE FORNITORE(
p_iva NUMBER(11),
nome_fornitore VARCHAR(10),
CONSTRAINT PK_FORNITORE PRIMARY KEY (p_iva)
);

--FORNITURA
CREATE TABLE FORNITURA(
idOrdine NUMBER(5),
data_acquisto DATE,
data_consegna DATE,
CONSTRAINT PK_FORNITURA PRIMARY KEY (idOrdine)
);
--------------------------------------------------
-- TABELLE TRANSIZIONE

-- SI ISCRIVE
CREATE TABLE SI_ISCRIVE(
CF_c1 VARCHAR(16),
numEvento_1 NUMBER(5),
data_iscrizione DATE,
CONSTRAINT PK_ISCRIZ PRIMARY KEY (CF_c1,numEvento_1),
CONSTRAINT FK_CLI FOREIGN KEY (CF_c1) REFERENCES CLIENTE (CF),
CONSTRAINT FK_EVE FOREIGN KEY (numEvento_1) REFERENCES EVENTO (numEvento)
);

-- ACQUISTA
CREATE TABLE ACQUISTA(
CF_c2 VARCHAR(16),
ISBN_f1 VARCHAR(20),
data_acquisto DATE,
num_copie NUMBER(2),
CONSTRAINT PK_ACQUIST PRIMARY KEY (CF_c2,ISBN_f1),
CONSTRAINT FK_CL FOREIGN KEY (CF_c2) REFERENCES CLIENTE (CF),
CONSTRAINT FK_FUM FOREIGN KEY (ISBN_f1) REFERENCES FUMETTO (ISBN)
);

--PRENOTA
CREATE TABLE PRENOTA(
CF_c3 VARCHAR(16),
ISBN_f2 VARCHAR(20),
data_prenotazione DATE,
CONSTRAINT PK_ACQUIST PRIMARY KEY (CF_c3,ISBN_f2),
CONSTRAINT FK_CL FOREIGN KEY (CF_c3) REFERENCES CLIENTE (CF),
CONSTRAINT FK_FUM FOREIGN KEY (ISBN_f2) REFERENCES FUMETTO (ISBN)
);

-- FORNISCE
CREATE TABLE FORNISCE(
idOrdine_f1 NUMBER(5),
ISBN_f3 VARCHAR(20), 
CONSTRAINT PK_FORNISCE PRIMARY KEY (idOrdine_f1,ISBN_f3),
CONSTRAINT FK_FORNITU FOREIGN KEY (idOrdine_f1) REFERENCES FORNITURA (idOrdine),
CONSTRAINT FK_FUME FOREIGN KEY (ISBN_f2) REFERENCES FUMETTO (ISBN)
);

--SPEDISCE
CREATE TABLE SPEDISCE(
idOrdine_f2 NUMBER(5),
p_iva_f1 NUMBER(11),
CONSTRAINT PK_SPEDISCE PRIMARY KEY (idOrdine_f2,p_iva_f1)
CONSTRAINT FK_FORNIT FOREIGN KEY (idOrdine_f2) REFERENCES FORNITURA (idOrdine),
CONSTRAINT FK_FORNI FOREIGN KEY (p_iva_f1) REFERENCES FORNITORE (p_iva)
);